### ISSUE TITLE
Threaded WSGI throws TypeError exception

### ISSUE THREAD

**Issue by thrawn01** [rtyler/Spawning#14]
Traceback (most recent call last):
  File "/home/thrawn/dev/apple-env/lib/python2.6/site-packages/eventlet-0.9.9-py2.6.egg/eventlet/wsgi.py", line 338, in handle_one_response
    result = self.application(self.environ, start_response)
TypeError: 'Proxy' object is not callable

The issue was introduced with commit
http://github.com/rtyler/Spawning/commit/d96e9657b533609657542dc545dfeba64c67735e

This commit depends on tpool changes only available in eventlet trunk. 
tpool.Proxy is not callable in version eventlet 0.9.9

The eventlet callable support was added here
http://bitbucket.org/which_linden/eventlet/changeset/ecef449748c0
Almost a month after the last 0.9.9 release tag

Checked out the latest version of eventlet from source and the error goes away. This means easy_installs of spawning are broken until eventlet releases 0.9.10.

**Comment by rtyler** [comment]
This should be resolved in the latest HEAD
