### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by nicferrier** [rtyler/Spawning#15]
Spawning is great, we're running woome.com on it and love it. But please can we have a new release because the deprecation errors of current released version are getting me down :-)

**Comment by rtyler** [comment]
I'm currently waiting on rdw@ to release an updated version of eventlet (0.9.12) after we discovered some issues with 0.9.10. Once that's out, Spawning should be ready for a new proper release :)

**Comment by nicferrier** [comment]
cool! thanks

**Comment by rtyler** [comment]
http://pypi.python.org/pypi/Spawning/0.9.4

**Comment by nicferrier** [comment]
yeah! saw it! thank you!
