### ISSUE TITLE
eventlet version

### ISSUE THREAD

**Issue by ashcrow** [rtyler/Spawning#17]
I see Spawning now requires eventlet 0.9.12 or greater per:

```
3a8604a8 (R. Tyler Ballance        2010-08-23 13:38:30 -0700 32) install_requires = ['eventlet >= 0.9.12',]
```

What features of 0.9.12 are being utilized? I ask because I may have to backport via patches to 0.9.9.

**Comment by rtyler** [comment]
Between 0.9.9 and 0.9.12 there aren't any changes that Spawning makes use of, I have a habit of bumping that version number just to make sure everybody gets the latest perf improvements in eventlet :)

**Comment by ashcrow** [comment]
Ah! OK, thanks for the super fast response!

**Comment by rtyler** [comment]
Think it's safe to close this :)
