### ISSUE TITLE
init.d script usage on Debian

### ISSUE THREAD

**Issue by bradwright** [rtyler/Spawning#5]
The conf.d and init.d scripts appear to be Gentoo specific. Any chance of a Debian-like flavour?

**Comment by rtyler** [comment]
I'm personally deploying to RHEL5, I'm also not using the init.d scripts, what would make them more Debian-like? (can has patch? :))

**Comment by bradwright** [comment]
Okay, I'll bite. :)

**Comment by rtyler** [comment]
Merged in with SHA: 712bed9bf01afcdadad60d5378aec8d6af161f86
