### ISSUE TITLE
Deprecated Eventlet APIs are used

### ISSUE THREAD

**Issue by jnurmine** [rtyler/Spawning#6]
Spawning prints out a lot of deprecation warnings.

/usr/lib/python2.5/site-packages/Spawning-0.9.3rc2-py2.5.egg/spawning/spawning_child.py:27: DeprecationWarning: eventlet.api is deprecated!  Nearly everything in it has moved to the eventlet module.  
  from eventlet import api, coros, greenio, wsgi  
/usr/lib/python2.5/site-packages/Spawning-0.9.3rc2-py2.5.egg/spawning/spawning_child.py:27: DeprecationWarning: eventlet.api is deprecated!  Nearly everything in it has moved to the eventlet module.
...
etc.

Eventlet version is 0.9.7, Spawning was 0.9.3rc2, but same issue exists in Git main branch too.

Command line like the following was used:

spawn --factory=spawning.django_factory.config_factory mydjangoapp.settings --port=1234

**Comment by rtyler** [comment]
Took care of this with SHA: 0ea35556d2154db663137b4693865a782f70e340 and SHA: 3be33e225f5582529b547be3bb5039cf215bf2d6
