### ISSUE TITLE
No pidfile created on Ubuntu

### ISSUE THREAD

**Issue by johnpaulett** [rtyler/Spawning#7]
On Ubuntu 9.10, using the spawning.debian init script, no pid file is created in the /var/run directory.  Thus the stop command does not work.

Since we are using the --background option of start-stop-daemon, it may make sense to include the --make-pidfile option as well (as suggested in start-stop-daemon's man page).

**Comment by rtyler** [comment]
SHA: d980e56a5640067cf70219cf09ac1a64c09b98df
