### ISSUE TITLE
Rename spawn script

### ISSUE THREAD

**Issue by rtyler** [rtyler/Spawning#8]
`/usr/bin/spawn` is silly, `/usr/bin/spawning` is teh bettar

**Comment by greut** [comment]
You're a bit little on the arguing aren't you?

**Comment by rtyler** [comment]
SHA: 14bec4cc6a22ca1cbea0d310e53441b709435305

**Comment by mgood** [comment]
Well, I'm not going to argue over which name is better, but this kind of change shouldn't happen during the RC phase.  I luckily only got bit in development, but I would expect this could break some people's production deployments when they don't notice, or forget that the executable's name has changed.  An "RC" tag should indicate that the API & features are locked down, and that upcoming changes will be for things like bug fixes.  Breaking people's deployments over a naming nit is silly.

**Comment by rtyler** [comment]
The RC tag is silly, I added it when I thought I was about to have some more time to add Spawning integration tests (but didn't).

This is to help get spawning packaged with Fedora, and in all likelihood the next release is going to be a big point release :)
